name: Check for Updates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0,2,4'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - run: git status

      - name: Setup Git Bot
        run: |
          git --version
          git config user.name 'daylin-bot'
          git config user.email 'bot@dayl.in'

      - name: Check for Update
        run: python update.py

      - name: Push Updates
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "chore: bump version"
            git tag $(grep version default.nix | sed -E 's/[[:space:]]+version = "(.*)";/v\1/')
            git push
            git push --tags
          fi
